= Near Field Communication (NFC) Library with NCI for Arduino =

This library allows you to interface with an NFC controller through the NFC Forum standardized NCI. To use it you will need a NFC controller, and the appropriate hardware to control it.

It implements the NFC Communication Interface (NCI) from the NFC Forum to interface with the NFC controller.

It supports tag detection at the moment, and has been tested with the following HW configuration:
* Intel Arduino/Genuino 101
* NXP PN7120 NFC Controller

It contains one sketch example to detect tags of types 1, 2, and 3 according to the NFC Forum for polling type A and F.
  
The NCI library is generic and should work with any other NFC controller which follows the NFC Forum specification.

To test with another NFC Controller HW:
* writes a new class that inherits the NfcHw class and which implements the virtual APIs (read, write, etc),
* allocates a new instance of that class and feed the constructor of NfcNCi with that objet.

From there the NfcNCi will be capable to interface directly with your NFC Controller through the HW connection
your class manages (i2c, uart, spi, etc).

For more information about this library please visit us at https://github.com/ThomasBuhot/arduino-nfc

== License ==

Copyright (c) Thomas Buhot. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
