= Near Field Communication (NFC) Library for Arduino =

This library allows you to control NFC controller. To use it you will need a NFC controller, and the appropriate hardware to control it.
It implements the NFC Communication Interface (NCI) from the NFC Forum to interface with the NFC controller.

For more information about this library please visit us at https://github.com/ThomasBuhot/arduino-nfc

== License ==

Copyright (c) Thomas Buhot. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
